name:                8cc-hs
version:             0.1.0.0
github:              "nwtgck/8cc-hs"
license:             BSD3
author:              "Ryo Ota"
maintainer:          "nwtgck@gmail.com"
copyright:           "2018 Ryo Ota"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            C compiler written in Haskell
category:            Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/nwtgck/8cc-hs#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  8cc-hs:
    main:                8cc.hs
    source-dirs:         8cc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - array
  elc-hs:
    main:                elc.hs
    source-dirs:         elc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - array

tests:
  8cc-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: []
